name       : xbitmaps
version    : 1.1.2
release    : 3
source     :
    - https://www.x.org/releases/individual/data/xbitmaps-1.1.2.tar.gz : 27e700e8ee02c43f7206f4eca8f1953ad15236cac95d7a0f08505c3f7d99c265
license    : GPL-3.0-or-later
component  : xorg.apps
summary    : X.Org Applications - xbitmaps
description: |
    The xbitmaps package contains bitmap images used by multiple applications.
patterns   :
    - /*
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
