name        : xbitmaps
version     : 1.1.1
release     : 2
source      :
    - http://xorg.freedesktop.org/releases/individual/data/xbitmaps-1.1.1.tar.bz2 : 3671b034356bbc4d32d052808cf646c940ec8b2d1913adac51b1453e41aa1e9d
license     : GPL-3.0+
summary     : X.Org Applications - xbitmaps
description : |
    The xbitmaps package contains bitmap images used by multiple applications.
patterns   :
    - /*
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
