name       : xbitmaps
version    : 1.1.3
release    : 4
source     :
    - https://www.x.org/releases/individual/data/xbitmaps-1.1.3.tar.gz : 93b433b7ff223c4685fdba583b4bd30f2706be2413a670021084422d85b0269d
license    : GPL-3.0-or-later
component  : xorg.apps
summary    : X.Org Applications - xbitmaps
description: |
    The xbitmaps package contains bitmap images used by multiple applications.
patterns   :
    - /*
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
